# Generated by Django 5.1.7 on 2025-03-21 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSensorData',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_temperature', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('brake_pressure', models.FloatField()),
                ('tire_pressure', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
